Epic Profile 3/3
alrche/iOS-FakeNFT-Team3 pull request #35
Opened 2024-12-18 06:46 UTC by alrche

Ссылка на борду - https://github.com/users/alrche/projects/1/views/1
Архитектура: MVVM
Верстка: кодом

Декомпозиция лежит в папке Docs с заполненным фактическим временем по 3 модулю Профиля + добавил общее время на весь эпик

2024-12-18 06:53 UTC, alrche commented on FakeNFT/Services/ProfileService.swift
> +        let dispatchQueue = DispatchQueue(label: "loading_fav_nfts_queue")
тут по аналогии с MyNFT сделал на отдельной очереди, чтобы не грузить main и не замедлять ui

2024-12-19 08:59 UTC, DGalbacheva approved these changes
Замечаний нет

2024-12-19 22:44 UTC, Kirchberg requested changes
Все классно и круто, у тебя получается очень хорошо писать код. Нашел только одно критическое замечание, которое нжно поправить, чтобы получить пустой экран, описал ниже подробнее:

⚠️ Что нужно исправить, чтобы перейти к мерджу с командой (это нужно исправить обязательно):

1. При попытке удаления последнего NFT появляется ошибка «Произошла ошибка во время снятия лайка». В соответствии с ТЗ ожидается, что будет показан пустой экран с надписью «У Вас все ещё нет NFT» при удалении последнего NFT из избранного, [[см. видео](https://disk.yandex.ru/i/lCrFm8qBwfGkHQ)](https://disk.yandex.ru/i/lCrFm8qBwfGkHQ).

Если возникнут вопросы, обязательно задавай их Наставнику или Наставнице!

2024-12-20 07:27 UTC, alrche commented
> Все классно и круто, у тебя получается очень хорошо писать код. Нашел только одно критическое замечание, которое нужно поправить, чтобы получить пустой экран, описал ниже подробнее:
> 
> ⚠️ Что нужно исправить, чтобы перейти к мерджу с командой (это нужно исправить обязательно):
> 
> 1. При попытке удаления последнего NFT появляется ошибка «Произошла ошибка во время снятия лайка». В соответствии с ТЗ ожидается, что будет показан пустой экран с надписью «У Вас все ещё нет NFT» при удалении последнего NFT из избранного, [см. видео](https://disk.yandex.ru/i/lCrFm8qBwfGkHQ).
> 
> Если возникнут вопросы, обязательно задавай их Наставнику или Наставнице!

спасибо большое за приятные слова!)

да, там глупая ошибка была при отправке запроса - прилетала 406, так как пытался отправить пустой массив с лайками, после дебага и поисков выяснил, что надо не пустой отправлять, а null, когда лайков не осталось - теперь работает :)

2024-12-20 08:34 UTC, Kirchberg approved these changes
Работа допущена до мерджа с основной веткой. Мердж должен происходить вместе со всей группой ✨

Возвращайся в следующей работе с вмердженными эпиками коллег. 
Эту часть работы нужно оформить в пул реквесте (develop->master), вся команда присылает на проверку одну и ту же ссылку. 
Нужно будет приложить скринкаст с демонстрацией своего эпика на симуляторе: 
рекомендую ссылку складывать не только в ПР, но и в Readme под описанием твоего эпика.

Предлагаю попробовать реализовать системный алерт с предложением об оценке приложения, либо попробовать сделать UI или Snapshot-тесты. В больших приложениях их используют для автоматизации тестирования, позволяя быстрее проверить перед отправкой в сторы новый релиз 🔫🤠

2024-12-20 08:48 UTC, merged